package kartkowka1;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    static Color kolorMiecza = null;
    
    public NewJFrame() {
        initComponents();
        zarejestrujJedi.addActionListener(new AkcjaSave());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListaWolnychJedi = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListaJedi = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        wprowadzNazweZakonu = new javax.swing.JTextField();
        wprowadzNazweJedi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        wybierzJediDoZakonu = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListaZakonowJedi = new javax.swing.JList<>();
        importZakony = new javax.swing.JButton();
        EksportZakony = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        zarejestrujJediWZakonie = new javax.swing.JButton();
        wyczysc1 = new javax.swing.JButton();
        importJedi = new javax.swing.JButton();
        eksportJedi = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        zarejestrujJedi = new javax.swing.JButton();
        wyczysc2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        boxKolorMiecza = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        przyciskJasna = new javax.swing.JRadioButton();
        przyciskCiemna = new javax.swing.JRadioButton();
        sliderMocMiecza = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("System zarządzania Jedi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Zakony Jedi");

        jListaWolnychJedi.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jScrollPane1.setViewportView(jListaWolnychJedi);

        jListaJedi.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jScrollPane2.setViewportView(jListaJedi);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Rejestracja Jedi");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Rejestracja Zakonu Jedi");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Jedi");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("Nazwa:");

        wprowadzNazweZakonu.setToolTipText("Wprowadz nazwe Zakonu Jedi");

        wprowadzNazweJedi.setToolTipText("Wprowadz nazwe Jedi");
        wprowadzNazweJedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wprowadzNazweJediActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setText("Nazwa:");

        wybierzJediDoZakonu.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        wybierzJediDoZakonu.setText("Wybierz");
        wybierzJediDoZakonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wybierzJediDoZakonuActionPerformed(evt);
            }
        });

        jListaZakonowJedi.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jScrollPane3.setViewportView(jListaZakonowJedi);

        importZakony.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        importZakony.setText("Import");
        importZakony.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importZakonyActionPerformed(evt);
            }
        });

        EksportZakony.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        EksportZakony.setText("Eksport");
        EksportZakony.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EksportZakonyActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setText("C:\\Users\\mHm_MaXi\\Desktop\\zakony.txt");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        zarejestrujJediWZakonie.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        zarejestrujJediWZakonie.setText("Zarejestruj");
        zarejestrujJediWZakonie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zarejestrujJediWZakonieActionPerformed(evt);
            }
        });

        wyczysc1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        wyczysc1.setText("Wyczysc");
        wyczysc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyczysc1ActionPerformed(evt);
            }
        });

        importJedi.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        importJedi.setText("Import");
        importJedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importJediActionPerformed(evt);
            }
        });

        eksportJedi.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        eksportJedi.setText("Eksport");
        eksportJedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eksportJediActionPerformed(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.setText("C:\\Users\\mHm_MaXi\\Desktop\\jedi.txt");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        zarejestrujJedi.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        zarejestrujJedi.setText("Zarejestruj");
        zarejestrujJedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zarejestrujJediActionPerformed(evt);
            }
        });

        wyczysc2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        wyczysc2.setText("Wyczysc");
        wyczysc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyczysc2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setText("Moc:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("Kolor miecza:");

        boxKolorMiecza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kolor niebieski", "kolor zielony", "kolor czerwony", "kolor bialy", "kolor czarny", "kolor zolty" }));
        boxKolorMiecza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxKolorMieczaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Strona mocy:");

        buttonGroup1.add(przyciskJasna);
        przyciskJasna.setText("jasna");
        przyciskJasna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskJasnaActionPerformed(evt);
            }
        });

        buttonGroup1.add(przyciskCiemna);
        przyciskCiemna.setText("ciemna");
        przyciskCiemna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskCiemnaActionPerformed(evt);
            }
        });

        sliderMocMiecza.setMajorTickSpacing(1000);
        sliderMocMiecza.setMaximum(1000);
        sliderMocMiecza.setPaintLabels(true);
        sliderMocMiecza.setValue(500);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel5)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addComponent(wprowadzNazweZakonu, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(wybierzJediDoZakonu, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(importZakony, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(EksportZakony, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jTextField3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(zarejestrujJediWZakonie, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(wyczysc1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(149, 149, 149))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(importJedi, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eksportJedi, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(24, 24, 24)
                                .addComponent(przyciskCiemna, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(przyciskJasna, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(zarejestrujJedi, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(wyczysc2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(wprowadzNazweJedi)
                                            .addComponent(boxKolorMiecza, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(sliderMocMiecza, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wprowadzNazweZakonu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wprowadzNazweJedi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(wybierzJediDoZakonu)
                                .addGap(76, 76, 76)
                                .addComponent(importZakony)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EksportZakony))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zarejestrujJediWZakonie)
                            .addComponent(wyczysc1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxKolorMiecza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sliderMocMiecza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(importJedi, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(przyciskCiemna)
                                        .addComponent(przyciskJasna)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eksportJedi))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zarejestrujJedi)
                            .addComponent(wyczysc2))
                        .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void wybierzJediDoZakonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wybierzJediDoZakonuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wybierzJediDoZakonuActionPerformed

    private void importZakonyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importZakonyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_importZakonyActionPerformed

    private void EksportZakonyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EksportZakonyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EksportZakonyActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void zarejestrujJediWZakonieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zarejestrujJediWZakonieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zarejestrujJediWZakonieActionPerformed

    private void wyczysc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyczysc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wyczysc1ActionPerformed

    private void importJediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importJediActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_importJediActionPerformed

    private void eksportJediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eksportJediActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eksportJediActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void zarejestrujJediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zarejestrujJediActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zarejestrujJediActionPerformed

    private void wyczysc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyczysc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wyczysc2ActionPerformed

    private void przyciskJasnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przyciskJasnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_przyciskJasnaActionPerformed

    private void przyciskCiemnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przyciskCiemnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_przyciskCiemnaActionPerformed

    private void boxKolorMieczaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxKolorMieczaActionPerformed
        pickColor(((JComboBox)evt.getSource()).getSelectedItem().toString());
    }//GEN-LAST:event_boxKolorMieczaActionPerformed

    private void wprowadzNazweJediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wprowadzNazweJediActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wprowadzNazweJediActionPerformed

    public static void pickColor(String nazwaKoloru){
       Color k = null;
        if(nazwaKoloru.equals("kolor niebieski"))
            k = Color.BLUE;
        else if(nazwaKoloru.equals("kolor zielony"))
            k = Color.GREEN;
        else if(nazwaKoloru.equals("kolor czerwony"))
            k = Color.RED;
        else if(nazwaKoloru.equals("kolor bialy"))
            k = Color.WHITE;
        else if(nazwaKoloru.equals("kolor czarny"))
            k = Color.BLACK;
        else if(nazwaKoloru.equals("kolor zolty"))
            k = Color.YELLOW;
        kolorMiecza = k;
    }
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EksportZakony;
    private javax.swing.JComboBox<String> boxKolorMiecza;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton eksportJedi;
    private javax.swing.JButton importJedi;
    private javax.swing.JButton importZakony;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListaJedi;
    private javax.swing.JList<String> jListaWolnychJedi;
    private javax.swing.JList<String> jListaZakonowJedi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JRadioButton przyciskCiemna;
    private javax.swing.JRadioButton przyciskJasna;
    private javax.swing.JSlider sliderMocMiecza;
    private javax.swing.JTextField wprowadzNazweJedi;
    private javax.swing.JTextField wprowadzNazweZakonu;
    private javax.swing.JButton wybierzJediDoZakonu;
    private javax.swing.JButton wyczysc1;
    private javax.swing.JButton wyczysc2;
    private javax.swing.JButton zarejestrujJedi;
    private javax.swing.JButton zarejestrujJediWZakonie;
    // End of variables declaration//GEN-END:variables

    private class AkcjaSave implements ActionListener {

        public AkcjaSave() {
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            if(!wprowadzNazweJedi.getText().isEmpty() && buttonGroup1.getSelection().isSelected()){
                
            }
        }
    }
}
